#!/bin/bash

set -xeuo pipefail

# bd=builddir
BUILD_DIR="${1:-bd}"
MYSELF="$(readlink -m $0)"
HERE="${MYSELF%/*}"
echo $HERE

(cd $HERE && bash -eu autogen.sh)

rm -rf "$BUILD_DIR"
mkdir "$BUILD_DIR"
cd "$BUILD_DIR"
echo '*' > .gitignore
"$HERE/configure" --enable-maintainer-mode --prefix=$PWD/DD "CFLAGS=-Wall -Wextra"

set +e
# We need to do some work regardless if make succeedes or fails. So here we
# don't stop on a failure, but preserve the exit code for later usage.
make all check
EXIT_CODE="$?"
set -e

grep . teg*test.log
exit "$EXIT_CODE"
