themes_dir = get_option('datadir') / 'teg' / 'themes'

install_subdir('TEG',
  install_dir: themes_dir,
  exclude_files: ['Makefile.am', 'Makefile.in'])

install_subdir('m2',
  install_dir: themes_dir,
  exclude_files: ['Makefile.am', 'Makefile.in', 'translate.c'])

install_subdir('teg_classic',
  install_dir: themes_dir,
  exclude_files: ['Makefile.am', 'Makefile.in', 'translate.c'])
