name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["ranft/teg:ul", "ranft/teg:d10"]

    container:
      image: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Meson
      run: python3 -m pip install --upgrade meson ninja

    - name: Build the software
      run: bash -x build
